### ISSUE TITLE
Fermi-KPOINTS.py

### ISSUE THREAD

**Issue by flower0226** [MTD-group/Fermi-Surface#5]
the KPOINTS i got from this script is like this (use default kx ky kz) : 

> 1 k-points for fermi-surface. K-mesh of 9x9x9
   2 1000
   3 Reciprocal
   4 0.0000 0.0000 0.0000 1
   5 0.0000 0.0000 0.0000 1
   6 0.0000 0.0000 0.0000 1
   7 0.0000 0.0000 0.0000 1
   8 0.0000 0.0000 0.0000 1
   9 0.0000 0.0000 0.0000 1
  10 0.0000 0.0000 0.0000 1
  11 0.0000 0.0000 0.0000 1
  12 0.0000 0.0000 0.0000 1
  13 0.0000 0.0000 1.0000 1
  14 0.0000 0.0000 0.0000 1
  15 0.0000 0.0000 0.0000 1
  16 0.0000 0.0000 0.0000 1
  17 0.0000 0.0000 0.0000 1
  18 0.0000 0.0000 0.0000 1
  19 0.0000 0.0000 0.0000 1
  20 0.0000 0.0000 0.0000 1
  21 0.0000 0.0000 0.0000 1
  22 0.0000 0.0000 0.0000 1
  23 0.0000 0.0000 1.0000 1
  24 0.0000 0.0000 0.0000 1
  25 0.0000 0.0000 0.0000 1
  26 0.0000 0.0000 0.0000 1

I'm not quite sure if it is correct, seems like very different from the example one.
Expected to receive any kind of respond! Tks!

**Comment by antonvF** [comment]
Hi! I came across the same problem. Seems to be the issue with python converting coordinated to integers automatically. So, just change this line in script:
`             data_array[i*(ky+1)*(kz+1)+j*(kz+1)+k,:-1]=[i/kx, j/ky, k/kz]`
to this one:
`            data_array[i*(ky+1)*(kz+1)+j*(kz+1)+k,:-1]=[i*1.0/kx, j*1.0/ky, k*1.0/kz]`
It should work.
